apiVersion: v1
kind: ConfigMap
metadata:
  name: cb-config
data:
  JAEGER_SAMPLE_RATIO: "0.0"
  LOG_LEVEL: "error"
  CB_CONTEXTBUS_ON: "1"
  CB_CONTEXTBUS_TRACE_SAMPLE_RATIO: "1.0"
  CB_PERF_METRIC: "1"